---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{DEVICE_NAME}}-{{DEVICE_ID}}-app
  name: {{DEVICE_NAME}}-{{DEVICE_ID}}-deployment
  namespace: device-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{DEVICE_NAME}}-{{DEVICE_ID}}-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{DEVICE_NAME}}-{{DEVICE_ID}}-app
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        name: bgd
        env:
        - name: COLOR
          value: "blue"
        resources: {}
        volumeMounts:
          - name: device-config
            mountPath: /tmp/device.yaml
            subPath: device.yaml
      volumes:
        - name: device-config
          configMap:
            name: {{DEVICE_NAME}}-{{DEVICE_ID}}-configmap
---
