---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-factory1-2367272-app
  name: test-factory1-2367272-deployment
  namespace: device-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-factory1-2367272-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-factory1-2367272-app
    spec:
      initContainers:
      - name: init-seed
        image: busybox
        command: ["sh", "-c"]
        args:
          - |
            if [ ! -f /data/.initialized ]; then
              echo "Seeding PVC from NFS..."
              cp -R /nfs/. /data/
              touch /data/.initialized
            else
              echo "PVC already initialized."
            fi
        volumeMounts:
          - name: app-data
            mountPath: /data
          - name: nfs-seed
            mountPath: /nfs
            readOnly: true

      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        name: bgd
        env:
        - name: COLOR
          value: "blue"
        resources: {}
        volumeMounts:
          - name: device-config
            mountPath: /tmp/device.yaml
            subPath: device.yaml
          - name: app-data
            mountPath: /data

      volumes:
        - name: device-config
          configMap:
            name: test-factory1-2367272-configmap
        - name: app-data
          persistentVolumeClaim:
            claimName: test-factory1-2367272-pvc
        - name: nfs-seed
          persistentVolumeClaim:
            claimName: nfs-seed
---
