---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{DEVICE_NAME}}-{{DEVICE_ID}}-app
  name: {{DEVICE_NAME}}-{{DEVICE_ID}}-deployment
  namespace: device-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{DEVICE_NAME}}-{{DEVICE_ID}}-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{DEVICE_NAME}}-{{DEVICE_ID}}-app
    spec:
      initContainers:
      - name: init-seed
        image: busybox
        command: ["sh", "-c"]
        args:
          - |
            if [ ! -f /data/.initialized ]; then
              echo "Seeding PVC from NFS..."
              cp -R /nfs/. /data/
              touch /data/.initialized
            else
              echo "PVC already initialized."
            fi
        volumeMounts:
          - name: app-data
            mountPath: /data
          - name: nfs-seed
            mountPath: /nfs
            readOnly: true

      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        name: bgd
        env:
        - name: COLOR
          value: "blue"
        resources: {}
        volumeMounts:
          - name: device-config
            mountPath: /tmp/device.yaml
            subPath: device.yaml
          - name: app-data
            mountPath: /data

      volumes:
        - name: device-config
          configMap:
            name: {{DEVICE_NAME}}-{{DEVICE_ID}}-configmap
        - name: app-data
          persistentVolumeClaim:
            claimName: {{DEVICE_NAME}}-{{DEVICE_ID}}-pvc

        - name: nfs-seed
          nfs:
            server: 192.168.68.172
            path: /data
---
